eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7800/eureka/
zuul:
  prefix: /api
  add-host-header: true
  routes:
    project-service: /project/**
    userinfo-service: /user/**
  sensitive-headers:
ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
local:
  filter:
    allowPaths:
      - /api/user/login
      - /api/user/info
      - /api/user/renewToken
  server-identity: 78bbf3a6-8834-4d5a-9095-62c3887417ae
  shared-secret: 46d34cb35b006fab90e74f4ba0fec16fe1ee7b671895fe0fa92e9401c0647c75b56e5e02f82e6e05f2f96ff7af22babe8d674fcb99e6eadee16bee7de86fc0ce
  url-permission-constant-map-file: UrlPermissionConstantMap.json
  url-permission-variable-map-file: UrlPermissionVariableMap.json
  cache-valid-time: 2500
  permanent-cache-valid-time: 3600000
  cache-concurrent-wait-time: 100
feign:
  httpclient:
    enabled: true
