eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7800/eureka/
zuul:
  prefix: /api
  add-host-header: true
  routes:
    project-service: /project/**
    userinfo-service: /userinfo/**
  sensitive-headers:
local:
  filter:
    allowPaths:
      - /api/user/login
  server-identity: 78bbf3a6-8834-4d5a-9095-62c3887417ae
  shared-secret: 46d34cb35b006fab90e74f4ba0fec16fe1ee7b671895fe0fa92e9401c0647c75b56e5e02f82e6e05f2f96ff7af22babe8d674fcb99e6eadee16bee7de86fc0ce